<?php
return [
	'innln\base\ArrayAccessTrait' => INNLN_PATH . '/base/ArrayAccessTrait.php',
	'innln\base\Arrayable' => INNLN_PATH . '/base/Arrayable.php',
	'innln\base\ArrayableTrait' => INNLN_PATH . '/base/ArrayableTrait.php',
	'innln\base\BaseObject' => INNLN_PATH . '/base/BaseObject.php',
	'innln\base\Component' => INNLN_PATH . '/base/Component.php',
	'innln\base\Configurable' => INNLN_PATH . '/base/Configurable.php',
	'innln\base\ErrorException' => INNLN_PATH . '/base/ErrorException.php',
	'innln\base\ErrorHandler' => INNLN_PATH . '/base/ErrorHandler.php',
	'innln\base\Event' => INNLN_PATH . '/base/Event.php',
	'innln\base\Exception' => INNLN_PATH . '/base/Exception.php',
	'innln\base\ExitException' => INNLN_PATH . '/base/ExitException.php',
	'innln\base\InlineAction' => INNLN_PATH . '/base/InlineAction.php',
	'innln\base\InvalidArgumentException' => INNLN_PATH . '/base/InvalidArgumentException.php',
	'innln\base\InvalidCallException' => INNLN_PATH . '/base/InvalidCallException.php',
	'innln\base\InvalidConfigException' => INNLN_PATH . '/base/InvalidConfigException.php',
	'innln\base\InvalidParamException' => INNLN_PATH . '/base/InvalidParamException.php',
	'innln\base\InvalidRouteException' => INNLN_PATH . '/base/InvalidRouteException.php',
	'innln\base\InvalidValueException' => INNLN_PATH . '/base/InvalidValueException.php',
	'innln\base\NotSupportedException' => INNLN_PATH . '/base/NotSupportedException.php',
	'innln\base\UnknownClassException' => INNLN_PATH . '/base/UnknownClassException.php',
	'innln\base\UnknownMethodException' => INNLN_PATH . '/base/UnknownMethodException.php',
	'innln\base\UnknownPropertyException' => INNLN_PATH . '/base/UnknownPropertyException.php',
	'innln\base\UserException' => INNLN_PATH . '/base/UserException.php',

	'innln\di\Container' => INNLN . '/di/Container.php',
	'innln\di\Instance' => INNLN . '/di/Instance.php',
	'innln\di\NotInstantiablerException' => INNLN . '/di/NotInstantiablerException.php',
	'innln\di\ServiceLocator' => INNLN . '/di/ServiceLocator.php',

	'innln\helpers\ArrayHelper' => INNLN . '/helpers/ArrayHelper.php',
	'innln\helpers\ReplaceArrayValue' => INNLN . '/helpers/ReplaceArrayValue.php',
	'innln\helpers\StringHelper' => INNLN . '/helpers/StringHelper.php',
	'innln\helpers\UnsetArrayValue' => INNLN . '/helpers/UnsetArrayValue.php',

	'innln\money\allocates\Average' => INNLN . '/money/allocates/Average.php',
	'innln\money\allocates\Ratio' => INNLN . '/money/allocates/Ratio.php',
	'innln\money\allocates\SchemeAbstract' => INNLN . '/money/allocates/SchemeAbstract.php',
	'innln\money\allocates\SchemeInterface' => INNLN . '/money/allocates/SchemeInterface.php',
	'innln\money\Currency' => INNLN . '/money/Currency.php',
	'innln\money\Money' => INNLN . '/money/Money.php',
];